DROP DATABASE IF EXISTS "s21_info";
CREATE DATABASE "s21_info";

\c s21_info;

SET datestyle = 'DMY';

DROP TABLE IF EXISTS Peers CASCADE;
CREATE TABLE Peers (
    nickname VARCHAR(255) PRIMARY KEY NOT NULL UNIQUE,
    birthday DATE NOT NULL
);

DROP TABLE IF EXISTS Tasks CASCADE;
CREATE TABLE Tasks (
    title VARCHAR(255) PRIMARY KEY NOT NULL,
    parent_task VARCHAR(255),
    xp INT
);

CREATE TYPE status AS ENUM (
    'Start',
    'Success',
    'Failure'
);

DROP TABLE IF EXISTS Checks CASCADE;
CREATE TABLE Checks (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    peer VARCHAR(255),
    task VARCHAR(255),
    date DATE,
    CONSTRAINT fk_checks_task FOREIGN KEY (task) REFERENCES Tasks(title)
);

DROP TABLE IF EXISTS P2P CASCADE;
CREATE TABLE P2P (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    check_id INT,
    checking_peer VARCHAR(255),
    state SMALLINT check (state >= 0 AND state <= 2), --поменять на тип status?
    time TIME,
    CONSTRAINT fk_p2p_check_id FOREIGN KEY (check_id) REFERENCES Checks(id),
    CONSTRAINT fk_p2p_checking_peer FOREIGN KEY (checking_peer) REFERENCES Peers(nickname)
);

DROP TABLE IF EXISTS Verter CASCADE;
CREATE TABLE Verter (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    check_id INT,
    state SMALLINT check (state >= 0 AND state <= 2), --поменять на тип status?
    time TIME,
    CONSTRAINT fk_verter_check_id FOREIGN KEY (check_id) REFERENCES Checks(id)
);

DROP TABLE IF EXISTS TransferredPoints CASCADE;
CREATE TABLE TransferredPoints (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    checking_peer VARCHAR(255),
    checked_peer VARCHAR(255),
    points_amount INT,
    CONSTRAINT fk_transferred_points_checking_peer FOREIGN KEY (checking_peer) REFERENCES Peers(nickname),
    CONSTRAINT fk_transferred_points_checked_peer FOREIGN KEY (checked_peer) REFERENCES Peers(nickname)
);

DROP TABLE IF EXISTS Friends CASCADE;
CREATE TABLE Friends (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    peer_1 VARCHAR(255),
    peer_2 VARCHAR(255),
    CONSTRAINT fk_friends_peer_1 FOREIGN KEY (peer_1) REFERENCES Peers(nickname),
    CONSTRAINT fk_friends_peer_2 FOREIGN KEY (peer_2) REFERENCES Peers(nickname)
);

DROP TABLE IF EXISTS Recommendations CASCADE;
CREATE TABLE Recommendations (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    peer VARCHAR(255),
    recommended_peer VARCHAR(255),
    CONSTRAINT fk_recommendations_peer FOREIGN KEY (peer) REFERENCES Peers(nickname),
    CONSTRAINT fk_recommendations_recommended_peer FOREIGN KEY (recommended_peer) REFERENCES Peers(nickname)
);

DROP TABLE IF EXISTS XP CASCADE;
CREATE TABLE XP (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    check_id INT,
    xp_amount INT,
    CONSTRAINT fk_xp_check_id FOREIGN KEY (check_id) REFERENCES Checks(id)
);

DROP TABLE IF EXISTS TimeTracking CASCADE;
CREATE TABLE TimeTracking (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    peer VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    time TIMESTAMP,
    state SMALLINT check (state >= 0 AND state <= 2), --поменять на тип status?
    CONSTRAINT fk_time_tracking_peer FOREIGN KEY (peer) REFERENCES Peers(nickname)
);