DROP DATABASE IF EXISTS "s21_info";
CREATE DATABASE "s21_info";

\c s21_info;

DROP TABLE IF EXISTS Peers CASCADE;
DROP TABLE IF EXISTS Tasks CASCADE;
DROP TABLE IF EXISTS Checks CASCADE;
DROP TABLE IF EXISTS P2P CASCADE;
DROP TABLE IF EXISTS Verter CASCADE;
DROP TABLE IF EXISTS TransferredPoints CASCADE;
DROP TABLE IF EXISTS Friends CASCADE;
DROP TABLE IF EXISTS Recommendations CASCADE;
DROP TABLE IF EXISTS XP CASCADE;
DROP TABLE IF EXISTS TimeTracking CASCADE;

CREATE TYPE status AS ENUM (
    'Start',
    'Success',
    'Failure'
    );

CREATE TABLE Peers
(
    nickname VARCHAR(255) PRIMARY KEY NOT NULL UNIQUE,
    birthday DATE                     NOT NULL
);

CREATE TABLE Tasks
(
    title       VARCHAR(255) PRIMARY KEY UNIQUE,
    parent_task VARCHAR(255),
    xp          INT,
    CONSTRAINT fk_tasks_parent_task FOREIGN KEY (parent_task) REFERENCES Tasks (title),
    CONSTRAINT check_not_eq CHECK (parent_task != title)
);

CREATE TABLE Checks
(
    id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    peer VARCHAR(255),
    task VARCHAR(255),
    date DATE,
    CONSTRAINT fk_checks_task FOREIGN KEY (task) REFERENCES Tasks (title),
    CONSTRAINT fk_checks_peer FOREIGN KEY (peer) REFERENCES Peers (nickname)
);

CREATE TABLE P2P
(
    id            INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    check_id      INT,
    checking_peer VARCHAR(255),
    state         status check (state IN ('Start', 'Success', 'Failure')),
    time          TIME,
    CONSTRAINT fk_p2p_check_id FOREIGN KEY (check_id) REFERENCES Checks (id),
    CONSTRAINT fk_p2p_checking_peer FOREIGN KEY (checking_peer) REFERENCES Peers (nickname)
);

CREATE TABLE Verter
(
    id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    check_id INT,
    state    status check (state IN ('Start', 'Success', 'Failure')),
    time     TIME,
    CONSTRAINT fk_verter_check_id FOREIGN KEY (check_id) REFERENCES Checks (id)
);

CREATE TABLE TransferredPoints
(
    id            INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    checking_peer VARCHAR(255),
    checked_peer  VARCHAR(255),
    points_amount INT,
    CONSTRAINT fk_transferred_points_checking_peer FOREIGN KEY (checking_peer) REFERENCES Peers (nickname),
    CONSTRAINT fk_transferred_points_checked_peer FOREIGN KEY (checked_peer) REFERENCES Peers (nickname),
    CONSTRAINT check_not_eq CHECK (checking_peer != checked_peer)
);

CREATE TABLE Friends
(
    id     INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    peer_1 VARCHAR(255),
    peer_2 VARCHAR(255),
    CONSTRAINT fk_friends_peer_1 FOREIGN KEY (peer_1) REFERENCES Peers (nickname),
    CONSTRAINT fk_friends_peer_2 FOREIGN KEY (peer_2) REFERENCES Peers (nickname),
    CONSTRAINT check_not_eq CHECK (peer_1 != peer_2)
);

CREATE TABLE Recommendations
(
    id               INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    peer             VARCHAR(255),
    recommended_peer VARCHAR(255),
    CONSTRAINT fk_recommendations_peer FOREIGN KEY (peer) REFERENCES Peers (nickname),
    CONSTRAINT fk_recommendations_recommended_peer FOREIGN KEY (recommended_peer) REFERENCES Peers (nickname),
    CONSTRAINT check_not_eq CHECK (peer != recommended_peer)
);

CREATE TABLE XP
(
    id        INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    check_id  INT,
    xp_amount INT,
    CONSTRAINT fk_xp_check_id FOREIGN KEY (check_id) REFERENCES Checks (id)
);

CREATE TABLE TimeTracking
(
    id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    peer     VARCHAR(255)                                     NOT NULL,
    date     DATE                                             NOT NULL,
    time     TIME,
    presence INT check (presence in (1, 2)),
    CONSTRAINT fk_time_tracking_peer FOREIGN KEY (peer) REFERENCES Peers (nickname)
);

SET datestyle = 'DMY';

DROP PROCEDURE IF EXISTS import_csv;
DROP PROCEDURE IF EXISTS export_csv;

-- This procedure imports data from a specified CSV file into a target table
CREATE OR REPLACE PROCEDURE import_csv(
    table_name TEXT,
    file_path TEXT,
    delim TEXT DEFAULT ';')
LANGUAGE plpgsql
AS $$
BEGIN
    EXECUTE format(
        'COPY %I FROM %L WITH (FORMAT CSV, HEADER, DELIMITER %L)',
        table_name, file_path, delim
        );
    RAISE NOTICE 'Data imported successfully from file % to table %', file_path, table_name;
END;
$$;

-- This procedure exports data from a table into a target specified CSV file
CREATE OR REPLACE PROCEDURE export_csv(
    table_name TEXT,
    file_path TEXT,
    delim TEXT DEFAULT ';')
LANGUAGE plpgsql
AS $$
BEGIN
    EXECUTE format(
        'COPY %I TO %L WITH (FORMAT CSV, HEADER, DELIMITER %L)',
        table_name, file_path, delim
        );
    RAISE NOTICE 'Data exported successfully from table % to file %', table_name, file_path;
END;
$$;

CALL import_csv('tasks', '/Users/hakekett/projects/SQL2_Info21_v1.0-1/datasets/tasks.csv');
CALL import_csv('peers', '/Users/hakekett/projects/SQL2_Info21_v1.0-1/datasets/peers.csv');
CALL import_csv('timetracking', '/Users/hakekett/projects/SQL2_Info21_v1.0-1/datasets/time_tracking.csv');
CALL import_csv('recommendations', '/Users/hakekett/projects/SQL2_Info21_v1.0-1/datasets/recommendations.csv');
CALL import_csv('friends', '/Users/hakekett/projects/SQL2_Info21_v1.0-1/datasets/friends.csv');
CALL import_csv('transferredpoints', '/Users/hakekett/projects/SQL2_Info21_v1.0-1/datasets/transferred_points.csv');
CALL import_csv('checks', '/Users/hakekett/projects/SQL2_Info21_v1.0-1/datasets/checks.csv');
CALL import_csv('p2p', '/Users/hakekett/projects/SQL2_Info21_v1.0-1/datasets/P2P.csv');
CALL import_csv('verter', '/Users/hakekett/projects/SQL2_Info21_v1.0-1/datasets/verter.csv');
CALL import_csv('xp', '/Users/hakekett/projects/SQL2_Info21_v1.0-1/datasets/xp.csv');