DROP DATABASE IF EXISTS "s21_info";
CREATE DATABASE "s21_info";

\c s21_info;

DROP TABLE IF EXISTS Peers CASCADE;
DROP TABLE IF EXISTS Tasks CASCADE;
DROP TABLE IF EXISTS Checks CASCADE;
DROP TABLE IF EXISTS P2P CASCADE;
DROP TABLE IF EXISTS Verter CASCADE;
DROP TABLE IF EXISTS TransferredPoints CASCADE;
DROP TABLE IF EXISTS Friends CASCADE;
DROP TABLE IF EXISTS Recommendations CASCADE;
DROP TABLE IF EXISTS XP CASCADE;
DROP TABLE IF EXISTS TimeTracking CASCADE;

SET datestyle = 'DMY';

CREATE TYPE status AS ENUM (
    'Start',
    'Success',
    'Failure'
    );

CREATE TABLE Peers (
nickname VARCHAR(255) PRIMARY KEY NOT NULL UNIQUE,
birthday DATE NOT NULL
);

CREATE TABLE Tasks (
title VARCHAR(255) PRIMARY KEY NOT NULL,
parent_task VARCHAR(255),
xp INT
);

CREATE TABLE Checks (
id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
peer VARCHAR(255),
task VARCHAR(255),
date DATE,
CONSTRAINT fk_checks_task FOREIGN KEY (task) REFERENCES Tasks(title)
);

CREATE TABLE P2P (
id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
check_id INT,
checking_peer VARCHAR(255),
state SMALLINT check (state >= 0 AND state <= 2), --поменять на тип status?
time TIME,
CONSTRAINT fk_p2p_check_id FOREIGN KEY (check_id) REFERENCES Checks(id),
CONSTRAINT fk_p2p_checking_peer FOREIGN KEY (checking_peer) REFERENCES Peers(nickname)
);

CREATE TABLE Verter (
id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
check_id INT,
state SMALLINT check (state >= 0 AND state <= 2), --поменять на тип status?
time TIME,
CONSTRAINT fk_verter_check_id FOREIGN KEY (check_id) REFERENCES Checks(id)
);

CREATE TABLE TransferredPoints (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    checking_peer VARCHAR(255),
    checked_peer VARCHAR(255),
    points_amount INT,
    CONSTRAINT fk_transferred_points_checking_peer FOREIGN KEY (checking_peer) REFERENCES Peers(nickname),
    CONSTRAINT fk_transferred_points_checked_peer FOREIGN KEY (checked_peer) REFERENCES Peers(nickname)
);

CREATE TABLE Friends (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    peer_1 VARCHAR(255),
    peer_2 VARCHAR(255),
    CONSTRAINT fk_friends_peer_1 FOREIGN KEY (peer_1) REFERENCES Peers(nickname),
    CONSTRAINT fk_friends_peer_2 FOREIGN KEY (peer_2) REFERENCES Peers(nickname)
);

CREATE TABLE Recommendations (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    peer VARCHAR(255),
    recommended_peer VARCHAR(255),
    CONSTRAINT fk_recommendations_peer FOREIGN KEY (peer) REFERENCES Peers(nickname),
    CONSTRAINT fk_recommendations_recommended_peer FOREIGN KEY (recommended_peer) REFERENCES Peers(nickname)
);

CREATE TABLE XP (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    check_id INT,
    xp_amount INT,
    CONSTRAINT fk_xp_check_id FOREIGN KEY (check_id) REFERENCES Checks(id)
);

CREATE TABLE TimeTracking (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    peer VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    time TIMESTAMP,
    state SMALLINT check (state >= 0 AND state <= 2), --поменять на тип status?
    CONSTRAINT fk_time_tracking_peer FOREIGN KEY (peer) REFERENCES Peers(nickname)
);